species:
  genome-size: 3.5e9
  germline-mutation-rate: 1.2e-08
  heterozygosity: 0.001
  ploidy:
    male:
      all: 2
      X: 1
      Y: 1
    female:
      all: 2
      X: 2
      Y: 0
samples:
  index:
    sex: female
    contamination:
      by: conta
      fraction: 0.1
  conta:
    sex: female
events:
  denovo:               "index:0.5 | index:1.0"
  rezessive_homozygous: "false"
  pos_ch_mother_strong: "false"
  pos_ch_father_strong: "false"
  pos_ch_weak:          "false"
  not_interesting:      "index:0.0"