samples: config/GiaB/samples.tsv
units: config/GiaB/units.tsv
groups: config/GiaB/groups.tsv

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 105
  # Genome build
  build: GRCh38

